GENERAL:
  SAVED_MODEL_NAME:
    - True
    - bert-base-uncased_try1

DATASET_PARAMS:
  DATASET_NAME: dair-ai/emotion      #Choose one of [ "dair-ai/emotion","jeffnyman/emotions","go_emotions"]
  BATCH_SIZE: 16

NEURON_DATASET_PARAMS:
  DATASET_NAME: layer_activations
  DATASET_FILENAME: data/activations_grads_anger_layer0.pt # Choose one of activations_grads_{sentiment}.pt
  BATCH_SIZE: 256
  ROW_NEURONS: True

MODELS_PARAMS:
  MODEL_NAME: bert-base-uncased


PIPLINE:
  step1:
    TITLE: GET_ACTIVATIONS
    ACTIVATE: False
    WANTED_LABELS: [ 'anger','fear' ]  #choose one of 'all' ['angry','happy'] ...
    CRITERION_NAME: CE
    OPTIMIZER_NAME: Adam
    LR_FEATURES: 0.0001
    LR_HEAD: 0.0001
    NUM_EPOCHS: 20
    WEIGHT_DECAY: 0.01
    MOMENTUM: 0.1
    FINE_TUNE_ONLY: False

  step2:
    TITLE: MODEL_TRAINING
    ACTIVATE: True
    MODEL: SAE
    WANTED_LABELS: [ 'anger','fear' ]  #choose one of 'all' ['angry','happy'] ...
    CRITERION_NAME: SAELoss
    SCHEDULER_NAME: CosineAnnealingLR # TODO- add this to the training, it uses this as default right now
    OPTIMIZER_NAME: Adam
    LR_SAE: 0.0001
    ALPHA_SPARSITY: 0.5
    WEIGHT_DECAY: 0.0001
    LANG_INPUT: 128
    LANG_D: 768
    OUT_SCALE: 0.25
    MOMENTUM: 0.1
    NUM_EPOCHS: 10
    TRAINING_PHASE: train_from_scratch   #choose one of [train_from_scratch, retrain, eval]
    FINE_TUNE_ONLY: False

  step3:
    TITLE: EXPLORE_WITH_SAE
    ACTIVATE: False
    MODEL: SAE
    WANTED_LABELS: [ 'anger','fear' ]  #choose one of 'all' ['angry','happy'] ...
    CRITERION_NAME: SAELoss
    SCHEDULER_NAME: CosineAnnealingLR # TODO- add this to the training, it uses this as default right now
    OPTIMIZER_NAME: Adam
    LR_SAE: 0.001
    ALPHA_SPARSITY: 0.5
    WEIGHT_DECAY: 0.0001
    LANG_INPUT: 128
    LANG_D: 768
    OUT_SCALE: 0.25
    MOMENTUM: 0.1
    NUM_EPOCHS: 10
    TRAINING_PHASE: train_from_scratch   #choose one of [train_from_scratch, retrain, eval]
    FINE_TUNE_ONLY: False


